/*
 * immudb REST API
 *
 * <b>IMPORTANT</b>: All <code>get</code> and <code>safeget</code> functions return <u>base64-encoded</u> keys and values, while all <code>set</code> and <code>safeset</code> functions expect <u>base64-encoded</u> inputs.
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SchemaSqlGetRequest {
    #[serde(rename = "table", skip_serializing_if = "Option::is_none")]
    pub table: Option<String>,
    #[serde(rename = "pkValues", skip_serializing_if = "Option::is_none")]
    pub pk_values: Option<Vec<crate::models::SchemaSqlValue>>,
    #[serde(rename = "atTx", skip_serializing_if = "Option::is_none")]
    pub at_tx: Option<String>,
    #[serde(rename = "sinceTx", skip_serializing_if = "Option::is_none")]
    pub since_tx: Option<String>,
}

impl SchemaSqlGetRequest {
    pub fn new() -> SchemaSqlGetRequest {
        SchemaSqlGetRequest {
            table: None,
            pk_values: None,
            at_tx: None,
            since_tx: None,
        }
    }
}


