/*
 * immudb REST API
 *
 * <b>IMPORTANT</b>: All <code>get</code> and <code>safeget</code> functions return <u>base64-encoded</u> keys and values, while all <code>set</code> and <code>safeset</code> functions expect <u>base64-encoded</u> inputs.
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SchemaVerifiableTx {
    #[serde(rename = "tx", skip_serializing_if = "Option::is_none")]
    pub tx: Option<Box<crate::models::SchemaTx>>,
    #[serde(rename = "dualProof", skip_serializing_if = "Option::is_none")]
    pub dual_proof: Option<Box<crate::models::SchemaDualProof>>,
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<Box<crate::models::SchemaSignature>>,
}

impl SchemaVerifiableTx {
    pub fn new() -> SchemaVerifiableTx {
        SchemaVerifiableTx {
            tx: None,
            dual_proof: None,
            signature: None,
        }
    }
}


