/*
 * immudb REST API
 *
 * <b>IMPORTANT</b>: All <code>get</code> and <code>safeget</code> functions return <u>base64-encoded</u> keys and values, while all <code>set</code> and <code>safeset</code> functions expect <u>base64-encoded</u> inputs.
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SchemaKeyListRequest {
    #[serde(rename = "keys", skip_serializing_if = "Option::is_none")]
    pub keys: Option<Vec<String>>,
    #[serde(rename = "sinceTx", skip_serializing_if = "Option::is_none")]
    pub since_tx: Option<String>,
}

impl SchemaKeyListRequest {
    pub fn new() -> SchemaKeyListRequest {
        SchemaKeyListRequest {
            keys: None,
            since_tx: None,
        }
    }
}


