/*
 * immudb REST API
 *
 * <b>IMPORTANT</b>: All <code>get</code> and <code>safeget</code> functions return <u>base64-encoded</u> keys and values, while all <code>set</code> and <code>safeset</code> functions expect <u>base64-encoded</u> inputs.
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SchemaSqlQueryRequest {
    #[serde(rename = "sql", skip_serializing_if = "Option::is_none")]
    pub sql: Option<String>,
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Vec<crate::models::SchemaNamedParam>>,
    #[serde(rename = "reuseSnapshot", skip_serializing_if = "Option::is_none")]
    pub reuse_snapshot: Option<bool>,
}

impl SchemaSqlQueryRequest {
    pub fn new() -> SchemaSqlQueryRequest {
        SchemaSqlQueryRequest {
            sql: None,
            params: None,
            reuse_snapshot: None,
        }
    }
}


