/*
 * immudb REST API
 *
 * <b>IMPORTANT</b>: All <code>get</code> and <code>safeget</code> functions return <u>base64-encoded</u> keys and values, while all <code>set</code> and <code>safeset</code> functions expect <u>base64-encoded</u> inputs.
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SchemaTxMetadata {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "prevAlh", skip_serializing_if = "Option::is_none")]
    pub prev_alh: Option<String>,
    #[serde(rename = "ts", skip_serializing_if = "Option::is_none")]
    pub ts: Option<String>,
    #[serde(rename = "nentries", skip_serializing_if = "Option::is_none")]
    pub nentries: Option<i32>,
    #[serde(rename = "eH", skip_serializing_if = "Option::is_none")]
    pub e_h: Option<String>,
    #[serde(rename = "blTxId", skip_serializing_if = "Option::is_none")]
    pub bl_tx_id: Option<String>,
    #[serde(rename = "blRoot", skip_serializing_if = "Option::is_none")]
    pub bl_root: Option<String>,
}

impl SchemaTxMetadata {
    pub fn new() -> SchemaTxMetadata {
        SchemaTxMetadata {
            id: None,
            prev_alh: None,
            ts: None,
            nentries: None,
            e_h: None,
            bl_tx_id: None,
            bl_root: None,
        }
    }
}


