/*
 * immudb REST API
 *
 * <b>IMPORTANT</b>: All <code>get</code> and <code>safeget</code> functions return <u>base64-encoded</u> keys and values, while all <code>set</code> and <code>safeset</code> functions expect <u>base64-encoded</u> inputs.
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SchemaTxEntry {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "hValue", skip_serializing_if = "Option::is_none")]
    pub h_value: Option<String>,
    #[serde(rename = "vLen", skip_serializing_if = "Option::is_none")]
    pub v_len: Option<i32>,
}

impl SchemaTxEntry {
    pub fn new() -> SchemaTxEntry {
        SchemaTxEntry {
            key: None,
            h_value: None,
            v_len: None,
        }
    }
}


