/*
 * immudb REST API
 *
 * <b>IMPORTANT</b>: All <code>get</code> and <code>safeget</code> functions return <u>base64-encoded</u> keys and values, while all <code>set</code> and <code>safeset</code> functions expect <u>base64-encoded</u> inputs.
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SchemaVerifiableEntry {
    #[serde(rename = "entry", skip_serializing_if = "Option::is_none")]
    pub entry: Option<Box<crate::models::SchemaEntry>>,
    #[serde(rename = "verifiableTx", skip_serializing_if = "Option::is_none")]
    pub verifiable_tx: Option<Box<crate::models::SchemaVerifiableTx>>,
    #[serde(rename = "inclusionProof", skip_serializing_if = "Option::is_none")]
    pub inclusion_proof: Option<Box<crate::models::SchemaInclusionProof>>,
}

impl SchemaVerifiableEntry {
    pub fn new() -> SchemaVerifiableEntry {
        SchemaVerifiableEntry {
            entry: None,
            verifiable_tx: None,
            inclusion_proof: None,
        }
    }
}


