/*
 * immudb REST API
 *
 * <b>IMPORTANT</b>: All <code>get</code> and <code>safeget</code> functions return <u>base64-encoded</u> keys and values, while all <code>set</code> and <code>safeset</code> functions expect <u>base64-encoded</u> inputs.
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SchemaZScanRequest {
    #[serde(rename = "set", skip_serializing_if = "Option::is_none")]
    pub set: Option<String>,
    #[serde(rename = "seekKey", skip_serializing_if = "Option::is_none")]
    pub seek_key: Option<String>,
    #[serde(rename = "seekScore", skip_serializing_if = "Option::is_none")]
    pub seek_score: Option<f64>,
    #[serde(rename = "seekAtTx", skip_serializing_if = "Option::is_none")]
    pub seek_at_tx: Option<String>,
    #[serde(rename = "inclusiveSeek", skip_serializing_if = "Option::is_none")]
    pub inclusive_seek: Option<bool>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<String>,
    #[serde(rename = "desc", skip_serializing_if = "Option::is_none")]
    pub desc: Option<bool>,
    #[serde(rename = "minScore", skip_serializing_if = "Option::is_none")]
    pub min_score: Option<Box<crate::models::SchemaScore>>,
    #[serde(rename = "maxScore", skip_serializing_if = "Option::is_none")]
    pub max_score: Option<Box<crate::models::SchemaScore>>,
    #[serde(rename = "sinceTx", skip_serializing_if = "Option::is_none")]
    pub since_tx: Option<String>,
    #[serde(rename = "noWait", skip_serializing_if = "Option::is_none")]
    pub no_wait: Option<bool>,
}

impl SchemaZScanRequest {
    pub fn new() -> SchemaZScanRequest {
        SchemaZScanRequest {
            set: None,
            seek_key: None,
            seek_score: None,
            seek_at_tx: None,
            inclusive_seek: None,
            limit: None,
            desc: None,
            min_score: None,
            max_score: None,
            since_tx: None,
            no_wait: None,
        }
    }
}


