/*
 * immudb REST API
 *
 * <b>IMPORTANT</b>: All <code>get</code> and <code>safeget</code> functions return <u>base64-encoded</u> keys and values, while all <code>set</code> and <code>safeset</code> functions expect <u>base64-encoded</u> inputs.
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SchemaOp {
    #[serde(rename = "kv", skip_serializing_if = "Option::is_none")]
    pub kv: Option<Box<crate::models::SchemaKeyValue>>,
    #[serde(rename = "zAdd", skip_serializing_if = "Option::is_none")]
    pub z_add: Option<Box<crate::models::SchemaZAddRequest>>,
    #[serde(rename = "ref", skip_serializing_if = "Option::is_none")]
    pub _ref: Option<Box<crate::models::SchemaReferenceRequest>>,
}

impl SchemaOp {
    pub fn new() -> SchemaOp {
        SchemaOp {
            kv: None,
            z_add: None,
            _ref: None,
        }
    }
}


