/*
 * immudb REST API
 *
 * <b>IMPORTANT</b>: All <code>get</code> and <code>safeget</code> functions return <u>base64-encoded</u> keys and values, while all <code>set</code> and <code>safeset</code> functions expect <u>base64-encoded</u> inputs.
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SchemaTxScanRequest {
    #[serde(rename = "initialTx", skip_serializing_if = "Option::is_none")]
    pub initial_tx: Option<String>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(rename = "desc", skip_serializing_if = "Option::is_none")]
    pub desc: Option<bool>,
}

impl SchemaTxScanRequest {
    pub fn new() -> SchemaTxScanRequest {
        SchemaTxScanRequest {
            initial_tx: None,
            limit: None,
            desc: None,
        }
    }
}


