/*
 * immudb REST API
 *
 * <b>IMPORTANT</b>: All <code>get</code> and <code>safeget</code> functions return <u>base64-encoded</u> keys and values, while all <code>set</code> and <code>safeset</code> functions expect <u>base64-encoded</u> inputs.
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SchemaZEntry {
    #[serde(rename = "set", skip_serializing_if = "Option::is_none")]
    pub set: Option<String>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "entry", skip_serializing_if = "Option::is_none")]
    pub entry: Option<Box<crate::models::SchemaEntry>>,
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<f64>,
    #[serde(rename = "atTx", skip_serializing_if = "Option::is_none")]
    pub at_tx: Option<String>,
}

impl SchemaZEntry {
    pub fn new() -> SchemaZEntry {
        SchemaZEntry {
            set: None,
            key: None,
            entry: None,
            score: None,
            at_tx: None,
        }
    }
}


