/*
 * immudb REST API
 *
 * <b>IMPORTANT</b>: All <code>get</code> and <code>safeget</code> functions return <u>base64-encoded</u> keys and values, while all <code>set</code> and <code>safeset</code> functions expect <u>base64-encoded</u> inputs.
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SchemaDatabaseSettings {
    #[serde(rename = "databaseName", skip_serializing_if = "Option::is_none")]
    pub database_name: Option<String>,
    #[serde(rename = "replica", skip_serializing_if = "Option::is_none")]
    pub replica: Option<bool>,
    #[serde(rename = "masterDatabase", skip_serializing_if = "Option::is_none")]
    pub master_database: Option<String>,
    #[serde(rename = "masterAddress", skip_serializing_if = "Option::is_none")]
    pub master_address: Option<String>,
    #[serde(rename = "masterPort", skip_serializing_if = "Option::is_none")]
    pub master_port: Option<i64>,
    #[serde(rename = "followerUsername", skip_serializing_if = "Option::is_none")]
    pub follower_username: Option<String>,
    #[serde(rename = "followerPassword", skip_serializing_if = "Option::is_none")]
    pub follower_password: Option<String>,
    #[serde(rename = "fileSize", skip_serializing_if = "Option::is_none")]
    pub file_size: Option<i64>,
    #[serde(rename = "maxKeyLen", skip_serializing_if = "Option::is_none")]
    pub max_key_len: Option<i64>,
    #[serde(rename = "maxValueLen", skip_serializing_if = "Option::is_none")]
    pub max_value_len: Option<i64>,
    #[serde(rename = "maxTxEntries", skip_serializing_if = "Option::is_none")]
    pub max_tx_entries: Option<i64>,
    #[serde(rename = "excludeCommitTime", skip_serializing_if = "Option::is_none")]
    pub exclude_commit_time: Option<bool>,
}

impl SchemaDatabaseSettings {
    pub fn new() -> SchemaDatabaseSettings {
        SchemaDatabaseSettings {
            database_name: None,
            replica: None,
            master_database: None,
            master_address: None,
            master_port: None,
            follower_username: None,
            follower_password: None,
            file_size: None,
            max_key_len: None,
            max_value_len: None,
            max_tx_entries: None,
            exclude_commit_time: None,
        }
    }
}


