/*
 * immudb REST API
 *
 * <b>IMPORTANT</b>: All <code>get</code> and <code>safeget</code> functions return <u>base64-encoded</u> keys and values, while all <code>set</code> and <code>safeset</code> functions expect <u>base64-encoded</u> inputs.
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SchemaPermissionAction {
    #[serde(rename = "GRANT")]
    GRANT,
    #[serde(rename = "REVOKE")]
    REVOKE,

}

impl ToString for SchemaPermissionAction {
    fn to_string(&self) -> String {
        match self {
            Self::GRANT => String::from("GRANT"),
            Self::REVOKE => String::from("REVOKE"),
        }
    }
}




