/*
 * immudb REST API
 *
 * <b>IMPORTANT</b>: All <code>get</code> and <code>safeget</code> functions return <u>base64-encoded</u> keys and values, while all <code>set</code> and <code>safeset</code> functions expect <u>base64-encoded</u> inputs.
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SchemaZAddRequest {
    #[serde(rename = "set", skip_serializing_if = "Option::is_none")]
    pub set: Option<String>,
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<f64>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "atTx", skip_serializing_if = "Option::is_none")]
    pub at_tx: Option<String>,
    #[serde(rename = "boundRef", skip_serializing_if = "Option::is_none")]
    pub bound_ref: Option<bool>,
    #[serde(rename = "noWait", skip_serializing_if = "Option::is_none")]
    pub no_wait: Option<bool>,
}

impl SchemaZAddRequest {
    pub fn new() -> SchemaZAddRequest {
        SchemaZAddRequest {
            set: None,
            score: None,
            key: None,
            at_tx: None,
            bound_ref: None,
            no_wait: None,
        }
    }
}


