/*
 * immudb REST API
 *
 * <b>IMPORTANT</b>: All <code>get</code> and <code>safeget</code> functions return <u>base64-encoded</u> keys and values, while all <code>set</code> and <code>safeset</code> functions expect <u>base64-encoded</u> inputs.
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SchemaHistoryRequest {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<String>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "desc", skip_serializing_if = "Option::is_none")]
    pub desc: Option<bool>,
    #[serde(rename = "sinceTx", skip_serializing_if = "Option::is_none")]
    pub since_tx: Option<String>,
}

impl SchemaHistoryRequest {
    pub fn new() -> SchemaHistoryRequest {
        SchemaHistoryRequest {
            key: None,
            offset: None,
            limit: None,
            desc: None,
            since_tx: None,
        }
    }
}


