/*
 * immudb REST API
 *
 * <b>IMPORTANT</b>: All <code>get</code> and <code>safeget</code> functions return <u>base64-encoded</u> keys and values, while all <code>set</code> and <code>safeset</code> functions expect <u>base64-encoded</u> inputs.
 *
 * The version of the OpenAPI document: version not set
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SchemaScanRequest {
    #[serde(rename = "seekKey", skip_serializing_if = "Option::is_none")]
    pub seek_key: Option<String>,
    #[serde(rename = "prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,
    #[serde(rename = "desc", skip_serializing_if = "Option::is_none")]
    pub desc: Option<bool>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<String>,
    #[serde(rename = "sinceTx", skip_serializing_if = "Option::is_none")]
    pub since_tx: Option<String>,
    #[serde(rename = "noWait", skip_serializing_if = "Option::is_none")]
    pub no_wait: Option<bool>,
}

impl SchemaScanRequest {
    pub fn new() -> SchemaScanRequest {
        SchemaScanRequest {
            seek_key: None,
            prefix: None,
            desc: None,
            limit: None,
            since_tx: None,
            no_wait: None,
        }
    }
}


